INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B002', 'Fisika Modern', 'Dewi Sartika', 'Maju Jaya', '2022', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B003', 'Sejarah Dunia', 'Agus Salim', 'Pustaka Kita', '2021', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B004', 'Seni Rupa Kontemporer', 'Anita Wardoyo', 'Kreatif Media', '2020', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B005', 'Puisi Pilihan', 'Budi Utomo', 'Cahaya Buku', '2018', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B001', 'Ilmu Komputer', 'Sandrak Nababan', 'Jaya Abadi', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B006', 'Ekonometrika', 'Siti Nurul', 'Maju Berkah', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B007', 'Manajemen Keuangan', 'Rizky Pratama', 'Pustaka Ekonomi', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B008', 'Anatomi Tubuh Manusia', 'Dian Syahputra', 'Cipta Medika', '2021', 'R24');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B009', 'Sosiologi Modern', 'Nina Dewi', 'Media Sosial', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B010', 'Seni Hukum', 'Arief Kusuma', 'Lex Artis', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B011', 'Olahraga dan Kesehatan', 'Yudi Prabowo', 'Maju Sehat', '2020', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B012', 'Algoritma Pemrograman', 'Dita Anggraeni', 'Informatika Press', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B013', 'Geografi Dunia', 'Aditya Wardhana', 'Pustaka Geografi', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B014', 'Filsafat Ilmu', 'Rudi Hermawan', 'Kritis Pustaka', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B015', 'Sejarah Ekonomi Indonesia', 'Rina Mustika', 'Ekonomika Nusantara', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B016', 'Pendidikan Bahasa Inggris', 'Devi Andriani', 'English Learning', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B017', 'Keperawatan Jiwa', 'Dinda Pratiwi', 'Nursing Care', '2018', 'R24');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B018', 'Kalkulus Dasar', 'Iqbal Yusuf', 'Mathematics Insight', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B019', 'Seni Teater', 'Adi Purnama', 'Creative Arts', '2019', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B020', 'Psikologi Abnormal', 'Rina Sulistyawati', 'Abnormal Psychology', '2020', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B021', 'Teknologi Informasi', 'Dimas Ramadhan', 'Tech Innovations', '2022', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B022', 'Manajemen Sumber Daya Manusia', 'Bella Putri', 'HR Management', '2018', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B023', 'Hukum Internasional', 'Arif Budiman', 'Global Law', '2019', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B024', 'Biologi Molekuler', 'Rini Kusuma', 'Molecular Biology', '2021', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B025', 'Seni Lukis', 'Hendri Susanto', 'Art Gallery', '2020', NULL);
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B026', 'Seni Lukis Abstrak', 'Ivan Santoso', 'Art Gallery', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B027', 'Panduan Penciptaan Patung', 'Sylvia Wijaya', 'Creative Sculptures', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B028', 'Fotografi Seni Kontemporer', 'Rendra Kusuma', 'Visual Arts Publishing', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B029', 'Seni Grafis Modern', 'Dewi Susanti', 'Graphic Arts Exploration', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B030', 'Desain Interior Minimalis', 'Putri Astuti', 'Minimalist Designs', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B031', 'Mengenal Seni Rupa Indonesia', 'Anton Wirawan', 'Indonesian Art Insights', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B032', 'Teknik Melukis Realistis', 'Sinta Wijaya', 'Realistic Painting Techniques', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B033', 'Karya Seni Video', 'Rizki Cahyadi', 'Video Art Creations', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B034', 'Seni Digital dan Teknologi', 'Lia Susanto', 'Digital Arts Integration', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B035', 'Ekspresi Seni Tari', 'Bambang Suryadi', 'Dance Art Expressions', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B036', 'Dasar-Dasar Fisika', 'Rahmat Wijaya', 'Penerbit Fisika', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B037', 'Kalkulus Lanjut', 'Siti Rahman', 'Matematika Maju', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B038', 'Biologi Sel', 'Diana Purnama', 'Bio Science', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B039', 'Kimia Organik', 'Hendra Susanto', 'Chemistry Insights', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B040', 'Matematika Diskrit', 'Budi Santoso', 'Digital Mathematics', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B041', 'Fisika Modern', 'Wulan Sari', 'Advanced Physics', '2023', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B042', 'Geologi Dasar', 'Dedy Pratama', 'Geoscience Fundamentals', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B043', 'Biokimia Molekuler', 'Lia Dewi', 'Molecular Biochemistry', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B044', 'Matematika Statistik', 'Agus Setiawan', 'Statistical Mathematics', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B045', 'Kimia Fisika', 'Rini Kusuma', 'Physical Chemistry Insights', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B046', 'Astronomi Dasar', 'Adi Nugroho', 'Basic Astronomy', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B047', 'Biologi Evolusioner', 'Nina Dewi', 'Evolutionary Biology', '2023', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B048', 'Matematika Terapan', 'Iqbal Yusuf', 'Applied Mathematics', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B049', 'Fisika Kuantum', 'Surya Pratama', 'Quantum Physics Explained', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B050', 'Kimia Organik Lanjut', 'Dian Susanti', 'Advanced Organic Chemistry', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B051', 'Biologi Molekuler Lanjut', 'Rudi Hermawan', 'Advanced Molecular Biology', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B052', 'Statistika Penelitian', 'Devi Andriani', 'Research Statistics', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B053', 'Geografi Perubahan Iklim', 'Arief Budiman', 'Climate Change Geography', '2023', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B054', 'Matematika Keuangan', 'Bella Putri', 'Financial Mathematics', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B055', 'Fisika Partikel', 'Arif Budiman', 'Particle Physics', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B056', 'Sosiologi Modern', 'Ari Wibowo', 'Pustaka Ilmu', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B057', 'Hukum Tata Negara', 'Diana Rahayu', 'Hukum Press', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B058', 'Psikologi Kepribadian', 'Farida Susanti', 'Majestic Mind', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B059', 'Hak Asasi Manusia', 'Rudi Prasetyo', 'Human Rights Publishing', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B060', 'Ekonomi Pembangunan', 'Siti Aminah', 'Maju Sejahtera', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B061', 'Antropologi Budaya', 'Ivan Putra', 'Cultural Insights', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B062', 'Hukum Perdata', 'Lina Dewi', 'Civil Law Perspectives', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B063', 'Politik Hukum', 'Rudi Santoso', 'Legal Politics', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B064', 'Sosiologi Hukum', 'Siska Wijaya', 'Law and Society', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B065', 'Edukasi Hukum', 'Diana Setiawan', 'Legal Education Insights', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B066', 'Psikologi Sosial', 'Agus Widodo', 'Social Psychology', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B067', 'Hukum Bisnis', 'Dewi Nurul', 'Business Law Principles', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B068', 'Ilmu Politik', 'Rina Fitri', 'Political Science Fundamentals', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B069', 'Sosiologi Ekonomi', 'Budi Utama', 'Economic Sociology', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B070', 'Hukum Internasional', 'Lia Pratama', 'International Law Perspectives', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B071', 'Psikologi Pendidikan', 'Santi Purnama', 'Educational Psychology', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B072', 'Politik Ekonomi', 'Rudi Setiawan', 'Economic Politics', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B073', 'Hukum Lingkungan', 'Dini Cahyani', 'Environmental Law Insights', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B074', 'Sosiologi Agama', 'Wahyu Widodo', 'Sociology of Religion', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B075', 'Kriminologi', 'Ratna Sari', 'Criminology Studies', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B076', 'Manajemen Olahraga', 'Iwan Setiawan', 'Sports Management Press', '2022', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B077', 'Fisiologi Latihan', 'Dewi Pratiwi', 'Exercise Physiology Publishing', '2021', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B078', 'Nutrisi untuk Atlet', 'Rudi Hermawan', 'Athlete Nutrition Publications', '2020', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B079', 'Psikologi Keolahragaan', 'Siska Wijaya', 'Sports Psychology Insights', '2019', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B080', 'Teknik Dasar Berenang', 'Budi Utomo', 'Swimming Basics Co.', '2018', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B081', 'Strategi Coaching', 'Rina Fitri', 'Coaching Strategies Handbook', '2023', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B082', 'Sejarah Olahraga Modern', 'Lina Dewi', 'Modern Sports History', '2022', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B083', 'Kesehatan dan Kebugaran', 'Agus Widodo', 'Health and Fitness Guide', '2021', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B084', 'Pengantar Fisioterapi', 'Dini Cahyani', 'Introduction to Physiotherapy', '2020', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B085', 'Ilmu Gizi untuk Atlet', 'Wahyu Widodo', 'Nutritional Science for Athletes', '2019', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B086', 'Manajemen Event Olahraga', 'Ratna Sari', 'Sports Event Management', '2018', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B087', 'Analisis Gerak Olahraga', 'Diana Setiawan', 'Sports Motion Analysis', '2023', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B088', 'Etika dalam Keolahragaan', 'Santi Purnama', 'Ethics in Sports', '2022', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B089', 'Pengembangan Keterampilan Bermain', 'Rudi Setiawan', 'Skill Development in Sports', '2021', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B090', 'Manajemen Kebugaran', 'Dewi Nurul', 'Fitness Management Principles', '2020', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B091', 'Pemulihan Cedera Olahraga', 'Lia Pratama', 'Sports Injury Recovery Guide', '2019', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B092', 'Pengukuran Prestasi Olahraga', 'Santi Purnama', 'Sports Performance Measurement', '2018', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B093', 'Olahraga dan Kesehatan Mental', 'Ratna Sari', 'Sports and Mental Health', '2023', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B094', 'Teknik Dasar Bulu Tangkis', 'Diana Rahayu', 'Basic Badminton Techniques', '2022', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B095', 'Manajemen Klub Olahraga', 'Iwan Setiawan', 'Sports Club Management', '2021', 'R25');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B096', 'Manajemen Keuangan', 'Agus Wijaya', 'Financial Management Publishing', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B097', 'Pemasaran Strategis', 'Sari Indah', 'Strategic Marketing Insights', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B098', 'Ekonomi Global', 'Budi Santoso', 'Global Economics Press', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B099', 'Bisnis Digital', 'Rina Fitri', 'Digital Business Handbook', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B100', 'Manajemen Operasional', 'Dewi Nurul', 'Operational Management Guide', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B101', 'Strategi Pemasaran Online', 'Lina Dewi', 'Online Marketing Strategies', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B102', 'Analisis Pasar', 'Rudi Setiawan', 'Market Analysis Handbook', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B103', 'Keuangan Bisnis', 'Siska Wijaya', 'Business Finance Essentials', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B104', 'Manajemen Sumber Daya Manusia', 'Iwan Setiawan', 'Human Resource Management', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B105', 'Inovasi Bisnis', 'Diana Rahayu', 'Business Innovation Guide', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B106', 'Perencanaan Bisnis', 'Ratna Sari', 'Business Planning Manual', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B107', 'Ekonomi Makro', 'Wahyu Widodo', 'Macroeconomics Basics', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B108', 'Manajemen Strategis', 'Lia Pratama', 'Strategic Management Principles', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B109', 'Bisnis Internasional', 'Santi Purnama', 'International Business Handbook', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B110', 'E-commerce', 'Rudi Hermawan', 'E-commerce Essentials', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B111', 'Akuntansi Bisnis', 'Dewi Sartika', 'Business Accounting Principles', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B112', 'Manajemen Keberlanjutan', 'Agus Salim', 'Sustainable Management Practices', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B113', 'Strategi Bisnis', 'Anita Wardoyo', 'Business Strategy Insights', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B114', 'Pajak Bisnis', 'Budi Utomo', 'Business Taxation Guide', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B115', 'Manajemen Proyek', 'Sandrak Nababan', 'Project Management Handbook', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B116', 'Pendidikan Inklusif', 'Diana Fitri', 'Pendidikan Inklusif Press', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B117', 'Psikologi Pendidikan', 'Surya Pratama', 'Psikologi Pendidikan Essentials', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B118', 'Kurikulum dan Pembelajaran', 'Lia Nurul', 'Kurikulum dan Pembelajaran Handbook', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B119', 'Manajemen Pendidikan', 'Wahyu Susilo', 'Manajemen Pendidikan Insights', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B120', 'Evaluasi Pendidikan', 'Rina Setiawan', 'Evaluasi Pendidikan Fundamentals', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B121', 'Pengembangan Kurikulum', 'Agus Wijaya', 'Pengembangan Kurikulum Handbook', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B122', 'Teori Belajar', 'Dewi Rahayu', 'Teori Belajar Basics', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B123', 'Bimbingan dan Konseling', 'Rudi Hermawan', 'Bimbingan dan Konseling Manual', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B124', 'Pendidikan Karakter', 'Siska Wijaya', 'Pendidikan Karakter Essentials', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B125', 'Teori Kepemimpinan Pendidikan', 'Lina Dewi', 'Leadership in Education Theories', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B126', 'Teknologi dalam Pendidikan', 'Agus Salim', 'Technology in Education Handbook', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B127', 'Pendidikan Anak Usia Dini', 'Anita Wardoyo', 'Early Childhood Education Guide', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B128', 'Metodologi Pembelajaran', 'Budi Utomo', 'Learning Methodology Basics', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B129', 'Pendidikan Jasmani', 'Dewi Sartika', 'Physical Education Fundamentals', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B130', 'Pendidikan Agama', 'Sandrak Nababan', 'Religious Education Handbook', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B131', 'Pendidikan Bahasa', 'Agus Wijaya', 'Language Education Essentials', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B132', 'Pendidikan Matematika', 'Rina Fitri', 'Mathematics Education Guide', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B133', 'Pendidikan Seni', 'Diana Rahayu', 'Art Education Basics', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B134', 'Pendidikan Teknik Informatika', 'Surya Pratama', 'Information Technology Education Insights', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B135', 'Pendidikan Vokasional', 'Lia Nurul', 'Vocational Education Handbook', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B136', 'Pendidikan Lingkungan', 'Wahyu Susilo', 'Environmental Education Fundamentals', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B137', 'Pendidikan Kesehatan', 'Rina Setiawan', 'Health Education Manual', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B138', 'Pendidikan Informatika', 'Agus Wijaya', 'Informatics Education Essentials', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B139', 'Pendidikan Geografi', 'Dewi Rahayu', 'Geography Education Guide', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B140', 'Pendidikan Sejarah', 'Rudi Hermawan', 'History Education Basics', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B141', 'Manajemen Keuangan', 'Dewi Sartika', 'Pustaka Jaya', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B142', 'Pemasaran Strategis', 'Agus Salim', 'Maju Jaya', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B143', 'Ekonomi Makro', 'Anita Wardoyo', 'Cahaya Buku', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B144', 'Manajemen Sumber Daya Manusia', 'Budi Utomo', 'Kreatif Media', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B145', 'Analisis Bisnis', 'Sandrak Nababan', 'Pustaka Kita', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B146', 'E-Bisnis', 'Diana Rahayu', 'Jaya Abadi', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B147', 'Kewirausahaan', 'Rudi Hermawan', 'Maju Jaya', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B148', 'Investasi', 'Lia Nurul', 'Cahaya Buku', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B149', 'Akuntansi Keuangan', 'Wahyu Susilo', 'Pustaka Jaya', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B150', 'Perbankan', 'Rina Setiawan', 'Kreatif Media', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B151', 'Manajemen Strategis', 'Dewi Rahayu', 'Pustaka Kita', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B152', 'Teori Ekonomi', 'Agus Wijaya', 'Jaya Abadi', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B153', 'Ekonometrika', 'Surya Pratama', 'Cahaya Buku', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B154', 'Bisnis Internasional', 'Lia Nurul', 'Maju Jaya', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B155', 'Pajak', 'Rina Setiawan', 'Kreatif Media', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B156', 'Manajemen Operasional', 'Budi Utomo', 'Pustaka Jaya', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B157', 'Analisis Investasi', 'Wahyu Susilo', 'Pustaka Kita', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B158', 'Ekonomi Islam', 'Diana Rahayu', 'Jaya Abadi', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B159', 'Manajemen Keuangan Internasional', 'Agus Wijaya', 'Cahaya Buku', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B160', 'Pasar Modal', 'Surya Pratama', 'Kreatif Media', '2021', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B161', 'Manajemen Risiko', 'Rudi Hermawan', 'Maju Jaya', '2020', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B162', 'Strategi Bisnis', 'Dewi Sartika', 'Pustaka Jaya', '2019', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B163', 'Ekonomi Kreatif', 'Anita Wardoyo', 'Pustaka Kita', '2018', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B164', 'Manajemen Proyek', 'Sandrak Nababan', 'Jaya Abadi', '2023', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B165', 'Bisnis Plan', 'Agus Salim', 'Cahaya Buku', '2022', 'R22');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B166', 'Teknologi Informasi', 'Andi Wijaya', 'Maju Jaya', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B167', 'Rekayasa Perangkat Lunak', 'Sari Utami', 'Cahaya Buku', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B168', 'Teknik Elektro', 'Budi Pratomo', 'Pustaka Jaya', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B169', 'Teknik Sipil', 'Rina Setiawan', 'Kreatif Media', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B170', 'Mekanika Fluida', 'Dewi Rahayu', 'Pustaka Kita', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B171', 'Kendali Otomatis', 'Agus Wijaya', 'Jaya Abadi', '2023', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B172', 'Sistem Komputer', 'Lia Nurul', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B173', 'Teknik Mesin', 'Surya Pratama', 'Maju Jaya', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B174', 'Manufaktur', 'Dewi Sartika', 'Pustaka Jaya', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B175', 'Instrumentasi Elektronik', 'Anita Wardoyo', 'Kreatif Media', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B176', 'Jaringan Komputer', 'Budi Utomo', 'Pustaka Kita', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B177', 'Arsitektur Komputer', 'Diana Rahayu', 'Jaya Abadi', '2023', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B178', 'Telekomunikasi', 'Agus Salim', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B179', 'Pemodelan Simulasi', 'Wahyu Susilo', 'Maju Jaya', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B180', 'Manajemen Proyek Teknik', 'Rudi Hermawan', 'Pustaka Jaya', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B181', 'Robotika', 'Sandrak Nababan', 'Kreatif Media', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B182', 'Teknik Kimia', 'Dewi Rahayu', 'Pustaka Kita', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B183', 'Pemrograman Terstruktur', 'Agus Wijaya', 'Jaya Abadi', '2023', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B184', 'Optimasi Sistem', 'Lia Nurul', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B185', 'Pengolahan Citra', 'Surya Pratama', 'Maju Jaya', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B186', 'Teknik Pengelasan', 'Dewi Sartika', 'Pustaka Jaya', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B187', 'Sistem Kontrol', 'Anita Wardoyo', 'Kreatif Media', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B188', 'Energi Terbarukan', 'Budi Utomo', 'Pustaka Kita', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B189', 'Ilmu Material', 'Diana Rahayu', 'Jaya Abadi', '2023', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B190', 'Teknik Lingkungan', 'Agus Salim', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B191', 'Metode Numerik', 'Wahyu Susilo', 'Maju Jaya', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B192', 'Teknik Pengukuran', 'Rudi Hermawan', 'Pustaka Jaya', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B193', 'Mikrokontroler', 'Sandrak Nababan', 'Kreatif Media', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B194', 'Sosiologi', 'Ahmad Surya', 'Pustaka Jaya', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B195', 'Hukum Internasional', 'Rini Kartika', 'Kreatif Media', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B196', 'Psikologi Umum', 'Satria Pratama', 'Maju Jaya', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B197', 'Ilmu Politik', 'Dewi Rahayu', 'Pustaka Kita', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B198', 'Ekonomi Pembangunan', 'Budi Utomo', 'Cahaya Buku', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B199', 'Hukum Acara Perdata', 'Anita Wardoyo', 'Jaya Abadi', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B200', 'Antropologi', 'Diana Rahayu', 'Pustaka Jaya', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B201', 'Kriminologi', 'Agus Salim', 'Kreatif Media', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B202', 'Sosiologi Hukum', 'Wahyu Susilo', 'Maju Jaya', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B203', 'Etika Profesi Hukum', 'Rudi Hermawan', 'Pustaka Kita', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B204', 'Kajian Gender', 'Lia Nurul', 'Cahaya Buku', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B205', 'Hak Asasi Manusia', 'Sandrak Nababan', 'Jaya Abadi', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B206', 'Teori Hukum', 'Dewi Sartika', 'Pustaka Jaya', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B207', 'Pendidikan Hukum', 'Agus Wijaya', 'Kreatif Media', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B208', 'Kesejahteraan Sosial', 'Budi Pratomo', 'Maju Jaya', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B209', 'Hubungan Internasional', 'Surya Pratama', 'Pustaka Kita', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B210', 'Teori Sosial', 'Dewi Rahayu', 'Cahaya Buku', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B211', 'Pengantar Hukum', 'Anita Wardoyo', 'Jaya Abadi', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B212', 'Sosiologi Politik', 'Diana Rahayu', 'Pustaka Jaya', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B213', 'Hukum Bisnis', 'Agus Salim', 'Kreatif Media', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B214', 'Pemikiran Hukum', 'Wahyu Susilo', 'Maju Jaya', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B215', 'Pendidikan Sosiologi', 'Rudi Hermawan', 'Pustaka Kita', '2019', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B216', 'Politik Hukum', 'Lia Nurul', 'Cahaya Buku', '2018', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B217', 'Sosiologi Ekonomi', 'Sandrak Nababan', 'Jaya Abadi', '2023', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B218', 'Hukum Keluarga', 'Dewi Sartika', 'Pustaka Jaya', '2022', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B219', 'Psikologi Sosial', 'Agus Wijaya', 'Kreatif Media', '2021', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B220', 'Ilmu Hukum', 'Budi Pratomo', 'Maju Jaya', '2020', 'R27');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B221', 'Seni Lukis', 'Rini Kartika', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B222', 'Seni Patung', 'Satria Pratama', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B223', 'Seni Grafis', 'Dewi Rahayu', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B224', 'Seni Digital', 'Budi Utomo', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B225', 'Seni Fotografi', 'Anita Wardoyo', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B226', 'Seni Teater', 'Rudi Hermawan', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B227', 'Seni Musik', 'Lia Nurul', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B228', 'Seni Tari', 'Sandrak Nababan', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B229', 'Seni Kriya', 'Dewi Sartika', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B230', 'Seni Batik', 'Agus Salim', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B231', 'Seni Keramik', 'Wahyu Susilo', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B232', 'Seni Rupa', 'Rina Kartika', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B233', 'Seni Kaligrafi', 'Surya Pratama', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B234', 'Seni Mural', 'Diana Rahayu', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B235', 'Seni Mozaik', 'Budi Pratomo', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B236', 'Seni Origami', 'Agus Wijaya', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B237', 'Seni Scrapbook', 'Rudi Hermawan', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B238', 'Seni Paper Quilling', 'Lia Nurul', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B239', 'Seni Digital Art', 'Sandrak Nababan', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B240', 'Seni Street Art', 'Dewi Sartika', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B241', 'Seni Body Painting', 'Agus Salim', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B242', 'Seni Nail Art', 'Wahyu Susilo', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B243', 'Seni Fashion Design', 'Rina Kartika', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B244', 'Seni Interior Design', 'Surya Pratama', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B245', 'Seni Landscape Design', 'Diana Rahayu', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B246', 'Seni Tattoo Design', 'Budi Pratomo', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B247', 'Seni Street Photography', 'Agus Wijaya', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B248', 'Seni Vexel Art', 'Rudi Hermawan', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B249', 'Seni Kinetic Art', 'Lia Nurul', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B250', 'Seni Light Painting', 'Sandrak Nababan', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B251', 'Seni Video Art', 'Dewi Sartika', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B252', 'Seni Interactive Art', 'Agus Salim', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B253', 'Seni Augmented Reality Art', 'Wahyu Susilo', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B254', 'Seni Virtual Reality Art', 'Rina Kartika', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B255', 'Seni 3D Printing Art', 'Surya Pratama', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B256', 'Seni Glass Art', 'Diana Rahayu', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B257', 'Seni Wood Carving', 'Budi Pratomo', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B258', 'Seni Metal Sculpture', 'Agus Wijaya', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B259', 'Seni Land Art', 'Rudi Hermawan', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B260', 'Seni Ice Sculpture', 'Lia Nurul', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B261', 'Seni Digital Painting', 'Rina Kartika', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B262', 'Seni Akrilik', 'Satria Pratama', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B263', 'Seni Cat Air', 'Dewi Rahayu', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B264', 'Seni Printmaking', 'Budi Utomo', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B265', 'Seni Serat', 'Anita Wardoyo', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B266', 'Seni Kinetik', 'Rudi Hermawan', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B267', 'Seni Video Mapping', 'Lia Nurul', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B268', 'Seni Digital Sculpture', 'Sandrak Nababan', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B269', 'Seni Interactive Installation', 'Dewi Sartika', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B270', 'Seni Projection Mapping', 'Agus Salim', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B271', 'Seni VJing', 'Wahyu Susilo', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B272', 'Seni Wearable Technology', 'Rina Kartika', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B273', 'Seni Data Visualization', 'Satria Pratama', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B274', 'Seni Generative Art', 'Dewi Rahayu', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B275', 'Seni BioArt', 'Budi Utomo', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B276', 'Seni Augmented Reality Sculpture', 'Anita Wardoyo', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B277', 'Seni Holography', 'Rudi Hermawan', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B278', 'Seni Projection Holography', 'Lia Nurul', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B279', 'Seni Mixed Media', 'Sandrak Nababan', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B280', 'Seni Digital Collage', 'Dewi Sartika', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B301', 'Seni Ceramah Motivasi', 'Rina Kartika', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B302', 'Seni Bisnis Sukses', 'Satria Pratama', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B303', 'Seni Kepemimpinan Inspiratif', 'Dewi Rahayu', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B304', 'Seni Komunikasi Efektif', 'Budi Utomo', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B305', 'Seni Manajemen Waktu', 'Anita Wardoyo', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B306', 'Seni Penulisan Kreatif', 'Rudi Hermawan', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B307', 'Seni Negosiasi Cerdas', 'Lia Nurul', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B308', 'Seni Public Speaking', 'Sandrak Nababan', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B309', 'Seni Presentasi Memukau', 'Dewi Sartika', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B310', 'Seni Mind Mapping', 'Agus Salim', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B311', 'Seni Problem Solving', 'Wahyu Susilo', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B312', 'Seni Keuangan Pribadi', 'Rina Kartika', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B313', 'Seni Kreativitas', 'Satria Pratama', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B314', 'Seni Pengembangan Diri', 'Dewi Rahayu', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B315', 'Seni Etika Bisnis', 'Budi Utomo', 'Maju Jaya', '2020', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B316', 'Seni Komunikasi Bisnis', 'Anita Wardoyo', 'Pustaka Kita', '2019', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B317', 'Seni Pemasaran Kreatif', 'Rudi Hermawan', 'Cahaya Buku', '2018', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B318', 'Seni Presentasi Bisnis', 'Lia Nurul', 'Jaya Abadi', '2023', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B319', 'Seni Kewirausahaan', 'Sandrak Nababan', 'Pustaka Jaya', '2022', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B320', 'Seni Strategi Bisnis', 'Dewi Sartika', 'Kreatif Media', '2021', 'R28');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B321', 'Pendidikan Anak Usia Dini', 'Nina Fitriana', 'Pustaka Jaya', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B322', 'Strategi Pembelajaran Inovatif', 'Hadi Santoso', 'Kreatif Media', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B323', 'Psikologi Pendidikan', 'Aulia Rahman', 'Maju Jaya', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B324', 'Teknologi Pendidikan', 'Dewi Kusumawati', 'Pustaka Kita', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B325', 'Manajemen Pendidikan', 'Budi Utomo', 'Cahaya Buku', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B326', 'Evaluasi Pembelajaran', 'Rina Kartika', 'Jaya Abadi', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B327', 'Kurikulum dan Pembelajaran', 'Satria Pratama', 'Pustaka Jaya', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B328', 'Pendidikan Karakter', 'Dewi Rahayu', 'Kreatif Media', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B329', 'Pendidikan Inklusif', 'Agus Salim', 'Maju Jaya', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B330', 'Pendidikan Kewarganegaraan', 'Anita Wardoyo', 'Pustaka Kita', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B331', 'Metode Pembelajaran', 'Rudi Hermawan', 'Cahaya Buku', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B332', 'Pendidikan Jasmani', 'Lia Nurul', 'Jaya Abadi', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B333', 'Pendidikan Anak Berkebutuhan Khusus', 'Sandrak Nababan', 'Pustaka Jaya', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B334', 'Pendidikan Agama Islam', 'Dewi Sartika', 'Kreatif Media', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B335', 'Pendidikan Bahasa Inggris', 'Nina Fitriana', 'Maju Jaya', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B336', 'Pendidikan Matematika', 'Hadi Santoso', 'Pustaka Kita', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B337', 'Pendidikan Seni Budaya', 'Aulia Rahman', 'Cahaya Buku', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B338', 'Pendidikan Teknik Informatika', 'Dewi Kusumawati', 'Jaya Abadi', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B339', 'Pendidikan Ekonomi', 'Budi Utomo', 'Pustaka Jaya', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B340', 'Pendidikan Fisika', 'Rina Kartika', 'Kreatif Media', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B341', 'Pendidikan Biologi', 'Satria Pratama', 'Maju Jaya', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B342', 'Pendidikan Geografi', 'Dewi Rahayu', 'Pustaka Kita', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B343', 'Pendidikan Sejarah', 'Agus Salim', 'Cahaya Buku', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B344', 'Pendidikan Pancasila', 'Anita Wardoyo', 'Jaya Abadi', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B345', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', 'Rudi Hermawan', 'Pustaka Jaya', '2022', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B346', 'Pendidikan Profesi Guru', 'Lia Nurul', 'Kreatif Media', '2021', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B347', 'Pendidikan Guru Sekolah Dasar', 'Sandrak Nababan', 'Maju Jaya', '2020', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B348', 'Pendidikan Anak Usia Sekolah', 'Dewi Sartika', 'Pustaka Kita', '2019', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B349', 'Pendidikan Luar Biasa', 'Nina Fitriana', 'Cahaya Buku', '2018', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B350', 'Pendidikan Vokasi', 'Hadi Santoso', 'Jaya Abadi', '2023', 'R26');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B382', 'Sejarah Asia Tenggara', 'I Made Bandem', 'Kreatif Media', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B383', 'Sejarah Dunia Kontemporer', 'Mochtar Naim', 'Maju Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B384', 'Sejarah Kebudayaan Islam', 'Abdurrahman Wahid', 'Pustaka Kita', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B385', 'Sejarah Peradaban China', 'Nurhadi', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B386', 'Sejarah Perang Dunia I', 'Adrian Vickers', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B387', 'Sejarah Perang Dunia II', 'I Wayan Warna', 'Pustaka Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B388', 'Sejarah Revolusi Industri', 'Dewi Kusumawati', 'Kreatif Media', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B389', 'Sejarah Filsafat Barat', 'Denny JA', 'Maju Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B390', 'Sejarah Seni Rupa', 'Dewi Rahayu', 'Pustaka Kita', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B391', 'Sejarah Kesenian Bali', 'S. Wirakartika', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B392', 'Sejarah Musik Dunia', 'A. Teeuw', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B393', 'Sejarah Pemikiran Ekonomi', 'Selo Sumardjan', 'Pustaka Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B394', 'Sejarah Politik Internasional', 'Dewa Made', 'Kreatif Media', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B395', 'Sejarah Teknologi Informasi', 'Agus Salim', 'Maju Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B396', 'Sejarah Kedokteran', 'Anita Wardoyo', 'Pustaka Kita', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B397', 'Sejarah Ilmu Pengetahuan', 'Rina Kartika', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B398', 'Sejarah Sastra Indonesia', 'Satria Pratama', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B399', 'Sejarah Hukum Internasional', 'Dewi Rahayu', 'Pustaka Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B400', 'Sejarah Astronomi', 'Lia Nurul', 'Kreatif Media', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B401', 'Sejarah Pendidikan Indonesia', 'Sandrak Nababan', 'Maju Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B402', 'Sejarah Arsitektur', 'Dewi Sartika', 'Pustaka Kita', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B403', 'Sejarah Geologi', 'Nina Fitriana', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B404', 'Sejarah Perbankan', 'Hadi Santoso', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B405', 'Sejarah Transportasi', 'Rudi Hermawan', 'Pustaka Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B406', 'Sejarah Budaya Jawa', 'Lia Nurul', 'Kreatif Media', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B407', 'Sejarah Politik Indonesia', 'Satria Pratama', 'Maju Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B408', 'Sejarah Agama Hindu', 'Dewi Rahayu', 'Pustaka Kita', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B409', 'Sejarah Perkembangan Komputer', 'Anita Wardoyo', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B410', 'Sejarah Perdagangan Internasional', 'Rina Kartika', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B411', 'Sejarah Linguistik', 'Agus Salim', 'Pustaka Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B412', 'Sejarah Sosiologi', 'Dewi Kusumawati', 'Kreatif Media', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B413', 'Sejarah Arkeologi', 'Dewa Made', 'Maju Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B414', 'Sejarah Pertanian', 'Nurhadi', 'Pustaka Kita', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B415', 'Sejarah Desain Grafis', 'A. Teeuw', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B416', 'Sejarah Psikologi', 'I Wayan Warna', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B417', 'Sejarah Peradaban Mesopotamia', 'Rina Kartika', 'Jaya Abadi', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B418', 'Sejarah Kekaisaran Romawi', 'Satria Pratama', 'Maju Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B419', 'Sejarah Perang Salib', 'Nurhadi', 'Pustaka Kita', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B420', 'Sejarah Kerajaan Majapahit', 'Lia Nurul', 'Kreatif Media', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B421', 'Sejarah Perang Dunia I', 'Dewi Rahayu', 'Cahaya Buku', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B422', 'Sejarah Revolusi Industri', 'Anita Wardoyo', 'Jaya Abadi', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B423', 'Sejarah Suku Maya', 'Hadi Santoso', 'Pustaka Jaya', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B424', 'Sejarah Dinasti Tang', 'Rudi Hermawan', 'Maju Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B425', 'Sejarah Kemerdekaan Indonesia', 'Dewa Made', 'Pustaka Kita', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B426', 'Sejarah Teori Evolusi', 'I Wayan Warna', 'Cahaya Buku', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B427', 'Sejarah Dinasti Joseon', 'Nina Fitriana', 'Kreatif Media', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B428', 'Sejarah Perang Dingin', 'Agus Salim', 'Jaya Abadi', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B429', 'Sejarah Perkembangan Fisika', 'Dewi Kusumawati', 'Pustaka Jaya', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B430', 'Sejarah Arsitektur Kuno', 'Rina Kartika', 'Maju Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B431', 'Sejarah Kesusastraan Indonesia', 'Satria Pratama', 'Cahaya Buku', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B432', 'Sejarah Kesultanan Melayu', 'Nurhadi', 'Pustaka Kita', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B433', 'Sejarah Pendidikan Islam', 'Lia Nurul', 'Kreatif Media', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B434', 'Sejarah Perkembangan Seni Rupa', 'Dewi Rahayu', 'Jaya Abadi', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B435', 'Sejarah Keperawatan', 'Anita Wardoyo', 'Pustaka Jaya', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B436', 'Sejarah Permainan Tradisional', 'Hadi Santoso', 'Maju Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B437', 'Sejarah Ilmu Pengetahuan', 'Rudi Hermawan', 'Cahaya Buku', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B438', 'Sejarah Kesenian Bali', 'Dewa Made', 'Kreatif Media', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B439', 'Sejarah Konsep Matematika', 'I Wayan Warna', 'Jaya Abadi', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B440', 'Sejarah Pemikiran Ekonomi', 'Nina Fitriana', 'Pustaka Kita', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B441', 'Sejarah Kebudayaan Cina', 'Agus Salim', 'Cahaya Buku', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B442', 'Sejarah Perkembangan Bahasa Indonesia', 'Dewi Kusumawati', 'Maju Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B443', 'Sejarah Ilmu Komputer', 'Rina Kartika', 'Pustaka Jaya', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B444', 'Sejarah Seni Musik', 'Satria Pratama', 'Kreatif Media', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B445', 'Sejarah Lingkungan Hidup', 'Nurhadi', 'Jaya Abadi', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B446', 'Sejarah Perkembangan Teknologi Informasi', 'Lia Nurul', 'Cahaya Buku', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B447', 'Sejarah Kesehatan Reproduksi', 'Dewi Rahayu', 'Pustaka Kita', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B448', 'Sejarah Astronomi', 'Anita Wardoyo', 'Maju Jaya', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B449', 'Sejarah Pendidikan Anak Usia Dini', 'Hadi Santoso', 'Cahaya Buku', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B450', 'Sejarah Etnisitas di Indonesia', 'Rudi Hermawan', 'Pustaka Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B451', 'Sejarah Perkembangan Psikologi', 'Dewa Made', 'Kreatif Media', '2019', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B452', 'Sejarah Politik Indonesia', 'I Wayan Warna', 'Jaya Abadi', '2018', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B453', 'Sejarah Hak Asasi Manusia', 'Nina Fitriana', 'Pustaka Kita', '2023', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B454', 'Sejarah Perkembangan Filosofi', 'Agus Salim', 'Cahaya Buku', '2022', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B455', 'Sejarah Kesehatan Mental', 'Dewi Kusumawati', 'Maju Jaya', '2021', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B456', 'Sejarah Sistem Operasi Komputer', 'Rina Kartika', 'Pustaka Jaya', '2020', 'R29');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B501', 'Agama Hindu: Sejarah dan Ajaran', 'I Made', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B502', 'Agama Buddha: Filosofi dan Praktik', 'Ratna Dewi', 'Pustaka Kita', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B503', 'Kristologi: Pemahaman Terhadap Kristus', 'Agus Salim', 'Jaya Abadi', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B504', 'Teologi Islam: Konsep dan Diskusi', 'Nina Fitriana', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B505', 'Kabbalah: Misteri Agama Yahudi', 'Dewi Rahayu', 'Maju Jaya', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B506', 'Sikhisme: Kepercayaan dan Tradisi', 'Anita Wardoyo', 'Pustaka Jaya', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B507', 'Taoisme: Filsafat dan Kebijaksanaan', 'Hadi Santoso', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B508', 'Bhagavad Gita: Kitab Suci Hindu', 'Lia Nurul', 'Jaya Abadi', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B509', 'Aliran-aliran dalam Kristen', 'Rina Kartika', 'Pustaka Kita', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B510', 'Pemikiran Keagamaan dalam Filsafat', 'Dewa Made', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B511', 'Kritik Terhadap Agama', 'Dewi Kusumawati', 'Maju Jaya', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B512', 'Ajaran-ajaran dalam Agama Konghucu', 'Rudi Hermawan', 'Pustaka Jaya', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B513', 'Psikologi Spiritualitas', 'Budi Utomo', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B514', 'Hindu-Buddha dalam Kehidupan Masyarakat', 'Agus Salim', 'Jaya Abadi', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B515', 'Peran Agama dalam Pembangunan', 'Nina Fitriana', 'Pustaka Kita', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B516', 'Sikap Toleransi antar Umat Beragama', 'Dewi Rahayu', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B517', 'Etika dalam Perspektif Keagamaan', 'Anita Wardoyo', 'Maju Jaya', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B518', 'Misticisme dalam Agama-agama Dunia', 'Hadi Santoso', 'Pustaka Jaya', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B519', 'Hak Asasi Manusia dalam Pandangan Agama', 'Lia Nurul', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B520', 'Teologi Pembebasan: Konsep dan Realitas', 'Rina Kartika', 'Jaya Abadi', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B521', 'Pentingnya Dialog antar Umat Beragama', 'Dewa Made', 'Pustaka Kita', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B522', 'Makna Ritual Keagamaan', 'Dewi Kusumawati', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B523', 'Agama dan Etika Bisnis', 'Budi Utomo', 'Maju Jaya', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B524', 'Interaksi Agama dan Budaya', 'Agus Salim', 'Pustaka Jaya', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B525', 'Islam Nusantara: Sejarah dan Kebudayaan', 'Nina Fitriana', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B526', 'Perbandingan Ajaran Agama Dunia', 'Dewi Rahayu', 'Jaya Abadi', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B527', 'Religiositas Generasi Milenial', 'Anita Wardoyo', 'Pustaka Kita', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B528', 'Pentingnya Pendidikan Keagamaan', 'Hadi Santoso', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B529', 'Tokoh-tokoh Spiritual Dunia', 'Lia Nurul', 'Maju Jaya', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B530', 'Refleksi Keberagamaan dalam Seni', 'Rudi Hermawan', 'Pustaka Jaya', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B531', 'Pendidikan Agama Islam', 'Muhammad Ahsan', 'Kementrian Pendidikan dan Kebudayaan', '2017', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B532', 'Dasar-dasar Agama Buddha', 'Ratna Dewi', 'Pustaka Kita', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B533', 'Etika dalam Agama Kristen', 'Agus Salim', 'Cahaya Buku', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B534', 'Hinduisme: Ajaran dan Ritual', 'Nina Fitriana', 'Jaya Abadi', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B535', 'Islam dan Pluralisme Agama', 'Dewi Rahayu', 'Maju Jaya', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B536', 'Agama Konghucu: Kepercayaan dan Amalan', 'Anita Wardoyo', 'Pustaka Jaya', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B537', 'Teologi Kristen: Sejarah dan Ajaran', 'Hadi Santoso', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B538', 'Budaya Spiritual dalam Islam', 'Lia Nurul', 'Jaya Abadi', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B539', 'Kritik terhadap Dogma Agama', 'Rina Kartika', 'Pustaka Kita', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B540', 'Filsafat Agama: Konsep Dasar', 'Dewa Made', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B541', 'Interaksi Agama dan Kebudayaan', 'Dewi Kusumawati', 'Maju Jaya', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B542', 'Pentingnya Studi Agama dalam Pendidikan', 'Budi Utomo', 'Pustaka Jaya', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B543', 'Kristologi: Pemahaman Terhadap Kristus', 'Rudi Hermawan', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B544', 'Ajaran-ajaran Agama Sikh', 'Muhammad Ahsan', 'Jaya Abadi', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B545', 'Mistisisme dalam Agama-agama Dunia', 'Ratna Dewi', 'Pustaka Kita', '2018', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B546', 'Islam dan Pemberdayaan Perempuan', 'Agus Salim', 'Cahaya Buku', '2023', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B547', 'Pentingnya Dialog Antar Umat Beragama', 'Nina Fitriana', 'Maju Jaya', '2022', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B548', 'Fenomena Keagamaan dalam Masyarakat', 'Dewi Rahayu', 'Pustaka Jaya', '2021', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B549', 'Teologi Pembebasan dalam Kekristenan', 'Anita Wardoyo', 'Cahaya Buku', '2020', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B550', 'Hak Asasi Manusia dalam Perspektif Agama', 'Hadi Santoso', 'Jaya Abadi', '2019', 'R30');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B551', 'Matematika Dasar', 'Dewi Sartika', 'Maju Jaya', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B552', 'Fisika untuk Pemula', 'Agus Salim', 'Pustaka Kita', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B553', 'Kimia Dasar', 'Anita Wardoyo', 'Kreatif Media', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B554', 'Biologi: Konsep dasar dan Aplikasi', 'Budi Utomo', 'Cahaya Buku', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B555', 'Aljabar Linear', 'Sandrak Nababan', 'Jaya Abadi', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B556', 'Geometri Lanjut', 'Dewi Kusumawati', 'Maju Jaya', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B557', 'Statistika Terapan', 'Rina Kartika', 'Pustaka Kita', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B558', 'Kalkulus: Teori dan Aplikasi', 'Lia Nurul', 'Cahaya Buku', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B559', 'Mekanika: Dasar-dasar Fisika', 'Hadi Santoso', 'Jaya Abadi', '2023', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B560', 'Ekologi: Sistem Kehidupan', 'Muhammad Ahsan', 'Maju Jaya', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B561', 'Sistem Pencernaan Manusia', 'Ratna Dewi', 'Pustaka Kita', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B562', 'Struktur Atom dan Sifat Periodik', 'Agus Salim', 'Cahaya Buku', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B563', 'Genetika: Dasar-dasar Pewarisan', 'Anita Wardoyo', 'Jaya Abadi', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B564', 'Mikrobiologi: Organisme Mikroskopis', 'Budi Utomo', 'Pustaka Kita', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B565', 'Dasar-dasar Kimia Organik', 'Sandrak Nababan', 'Maju Jaya', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B566', 'Biokimia: Proses dan Metabolisme', 'Dewi Kusumawati', 'Cahaya Buku', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B567', 'Algoritma dan Pemrograman', 'Rina Kartika', 'Jaya Abadi', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B568', 'Pemrosesan Citra Digital', 'Lia Nurul', 'Pustaka Kita', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B569', 'Matematika Diskrit', 'Hadi Santoso', 'Cahaya Buku', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B570', 'Sistem Informasi Geografis', 'Muhammad Ahsan', 'Jaya Abadi', '2023', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B571', 'Dasar-dasar Biologi Sel', 'Ratna Dewi', 'Maju Jaya', '2018', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B572', 'Teori Informasi dan Pengkodean', 'Agus Salim', 'Pustaka Kita', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B573', 'Pengantar Ilmu Astronomi', 'Anita Wardoyo', 'Cahaya Buku', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B574', 'Dasar-dasar Logika Matematika', 'Budi Utomo', 'Jaya Abadi', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B575', 'Fisika Modern: Konsep dan Aplikasi', 'Sandrak Nababan', 'Pustaka Kita', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B576', 'Kimia Fisika: Kajian Molekuler', 'Dewi Kusumawati', 'Cahaya Buku', '2019', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B577', 'Biologi Evolusioner', 'Rina Kartika', 'Jaya Abadi', '2020', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B578', 'Teori Graf: Konsep dan Implementasi', 'Lia Nurul', 'Pustaka Kita', '2021', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B579', 'Matematika Keuangan', 'Hadi Santoso', 'Cahaya Buku', '2022', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B580', 'Teknologi Pangan: Prinsip dan Aplikasi', 'Muhammad Ahsan', 'Jaya Abadi', '2023', 'R23');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B581', 'Teknik Sipil: Dasar-dasar Konstruksi', 'Dewi Sartika', 'Maju Jaya', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B582', 'Teknik Mesin: Prinsip dan Aplikasi', 'Agus Salim', 'Pustaka Kita', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B583', 'Teknik Elektro: Sistem Tenaga Listrik', 'Anita Wardoyo', 'Kreatif Media', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B584', 'Teknik Kimia: Proses Manufaktur', 'Budi Utomo', 'Cahaya Buku', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B585', 'Teknik Informatika: Pemrograman Lanjut', 'Sandrak Nababan', 'Jaya Abadi', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B586', 'Teknik Lingkungan: Pengelolaan Limbah', 'Dewi Kusumawati', 'Maju Jaya', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B587', 'Teknik Industri: Manajemen Produksi', 'Rina Kartika', 'Pustaka Kita', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B588', 'Teknik Geologi: Penelitian Sumber Daya Alam', 'Lia Nurul', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B589', 'Teknik Perkapalan: Desain Kapal Laut', 'Hadi Santoso', 'Jaya Abadi', '2023', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B590', 'Teknik Perminyakan: Pengeboran Sumur', 'Muhammad Ahsan', 'Maju Jaya', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B591', 'Teknik Metalurgi: Proses Peleburan Logam', 'Ratna Dewi', 'Pustaka Kita', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B592', 'Teknik Astronotika: Pengembangan Pesawat Antariksa', 'Agus Salim', 'Cahaya Buku', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B593', 'Teknik Nuklir: Aplikasi Energi Nuklir', 'Anita Wardoyo', 'Jaya Abadi', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B594', 'Teknik Biomedis: Inovasi Teknologi Kesehatan', 'Budi Utomo', 'Pustaka Kita', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B595', 'Teknik Telekomunikasi: Jaringan Komunikasi Digital', 'Sandrak Nababan', 'Maju Jaya', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B596', 'Teknik Elektronika: Perancangan Sistem Kontrol', 'Dewi Kusumawati', 'Cahaya Buku', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B597', 'Teknik Pertambangan: Penambangan Mineral', 'Rina Kartika', 'Jaya Abadi', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B598', 'Teknik Planologi: Perencanaan Wilayah Kota', 'Lia Nurul', 'Pustaka Kita', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B599', 'Teknik Penerbangan: Dinamika Pesawat Udara', 'Hadi Santoso', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B600', 'Teknik Elektromedik: Perangkat Kesehatan Elektronik', 'Muhammad Ahsan', 'Jaya Abadi', '2023', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B601', 'Teknik Material: Pengembangan Bahan Konstruksi', 'Ratna Dewi', 'Maju Jaya', '2018', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B602', 'Teknik Robotika: Desain dan Kontrol Robot', 'Agus Salim', 'Pustaka Kita', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B603', 'Teknik Energi: Konversi dan Manajemen Energi', 'Anita Wardoyo', 'Cahaya Buku', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B604', 'Teknik Kelistrikan: Sistem Tenaga Listrik', 'Budi Utomo', 'Jaya Abadi', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B605', 'Teknik Sistem Kontrol: Teori dan Aplikasi', 'Sandrak Nababan', 'Pustaka Kita', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B606', 'Teknik Rekayasa Perangkat Lunak: Pengembangan Aplikasi', 'Dewi Kusumawati', 'Cahaya Buku', '2019', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B607', 'Teknik Hidrologi: Analisis Air Tanah', 'Rina Kartika', 'Jaya Abadi', '2020', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B608', 'Teknik Transportasi: Perencanaan Infrastruktur Jalan', 'Lia Nurul', 'Pustaka Kita', '2021', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B609', 'Teknik Komputer: Arsitektur dan Organisasi Komputer', 'Hadi Santoso', 'Cahaya Buku', '2022', 'R21');
INSERT INTO "buku" ("id_buku", "judul", "nm_pengarang", "nm_penerbit", "thn_terbit", "no_rak") VALUES ('B700', 'Teknik Astronomi: Pemahaman Benda Langit', 'Muhammad Ahsan', 'Jaya Abadi', '2023', 'R21');
