INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('001', 'Pramoedya Ananta Toer');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('002', 'Tere Liye');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('003', 'Andrea Hirata');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('004', 'Dee Lestari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('005', 'Ayu Utami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('006', 'Dewi Lestari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('007', 'Eka Kurniawan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('008', 'Habiburrahman El-Shirazy');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('009', 'Leila S. Chudori');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('010', 'Seno Gumira Ajidarma');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('011', 'Pramoedya M. Tjan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('012', 'Laksmi Pamuntjak');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('013', 'Sapardi Djoko Damono');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('014', 'Ayu Prameswari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('015', 'Sitta Karina');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('016', 'Asma Nadia');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('017', 'N.H. Dini');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('018', 'Mira W.');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('019', 'Tia Setiawati');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('020', 'Helvy Tiana Rosa');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('021', 'Andrea Hirata');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('022', 'Ayu Utami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('023', 'Eka Kurniawan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('024', 'Intan Paramaditha');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('025', 'George Junus Aditjondro');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('026', 'Ags. Arya Dipayana');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('027', 'Leon Agusta');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('028', 'Akhudiat');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('029', 'Sutan Takdir Alisjahbana');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('030', 'Swami Anand Krishna');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('031', 'Ang Jan Goan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('032', 'Chairil Anwar');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('033', 'Dewi Lestari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('034', 'Khairani Barokka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('035', 'Sapardi Djoko Damono');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('036', 'Ayu Prameswari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('037', 'Sitta Karina');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('038', 'Asma Nadia');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('039', 'N.H. Dini');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('040', 'Mira W.');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('041', 'Tia Setiawati');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('042', 'Helvy Tiana Rosa');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('043', 'Dewi Lestari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('044', 'Khairani Barokka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('045', 'Andrea Hirata');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('046', 'Ayu Utami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('047', 'Pramoedya Ananta Toer');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('048', 'Eka Kurniawan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('049', 'Intan Paramaditha');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('050', 'Ari Ansori');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('051', 'Tash Aw');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('052', 'Tan Twan Eng');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('053', 'Yangsze Choo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('054', 'Preeta Samarasan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('055', 'Shamini Flint');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('056', 'Rani Manicka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('057', 'Samantha Shu Ting');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('058', 'Chin Kee Onn');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('059', 'Fadzlishah Johanabas');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('060', 'Rumaizah Abu Bakar');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('061', 'Sofea Mohd');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('062', 'Lily Haslina Nasir');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('063', 'Aini Alias');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('064', 'Jamal Raslan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('065', 'Sabri Zain');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('066', 'Karim Raslan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('067', 'Zen Cho');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('068', 'Siti Hawa Salleh');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('069', 'Chiew-Siah Tei');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('070', 'Ridhwan Saidi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('071', 'Shih-Li Kow');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('072', 'Wong Phui Nam');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('073', 'Che Husna Azhari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('074', 'Rozlan Mohd Noor');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('075', 'Huzir Sulaiman');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('076', 'Azreena Aziz');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('077', 'Tina Isaacs');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('078', 'Azahari Abdullah');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('079', 'Faisal Tehrani');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('080', 'Anuar Othman');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('081', 'Yazid Hussein');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('082', 'Sharifah Mastura Al Jifree');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('083', 'K.S. Maniam');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('084', 'Tan Kim Hock');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('085', 'Fa Abdul');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('086', 'Megat Ishak');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('087', 'Usman Awang');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('088', 'Sufian Abas');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('089', 'Wan Nor Azriq');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('090', 'Norhayati Berahim');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('091', 'Shahnon Ahmad');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('092', 'Anwar Ridhwan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('093', 'Ridhwan Saidi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('094', 'Zakaria Ali');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('095', 'Kassim Ahmad');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('096', 'A. Samad Said');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('097', 'Ahmad Tohari');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('098', 'Malayajournalist');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('099', 'Lutfi Irwan Ibrahim');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('100', 'Roslan Rahman');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('101', 'Ajin Panjapan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('102', 'Phraya Anuman Rajadhon');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('103', 'Anusorn Mongkolkarn');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('104', 'Arak Amornsupasiri');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('105', 'Seni Saowapong');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('106', 'Pitchaya Sudbanthad');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('107', 'Chart Korbjitti');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('108', 'Kukrit Pramoj');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('109', 'Prabda Yoon');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('110', 'Rattawut Lapcharoensap');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('111', 'Emmanuelle Arsan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('112', 'Sunisa Manning');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('113', 'Pamda Bure');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('114', 'Tew Bunnag');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('115', 'Sukhbir Cheema');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('116', 'Lakambini A. Sitoy');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('117', 'Supinya Klangnarong');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('118', 'Kanjana Meelarp');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('119', 'Bantita Ngamcharoen');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('120', 'Ploy Kaengkan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('121', 'Nirut Sirijanya');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('122', 'Kamol Siripipat');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('123', 'Pairoj Pratoomma');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('124', 'Chanwit Mankhong');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('125', 'Wichit Saiklao');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('126', 'Kriengsak Chareonwongsak');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('127', 'Wannasingh Prasertkul');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('128', 'Bundit Ungrangsee');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('129', 'Manrat Saithanu');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('130', 'Tara E. Heidger');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('131', 'Prapas Cholsaranon');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('201', 'Haruki Murakami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('202', 'Yukio Mishima');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('203', 'Natsume Soseki');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('204', 'Banana Yoshimoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('205', 'Murasaki Shikibu');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('206', 'Ryunosuke Akutagawa');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('207', 'Kenzaburo Oe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('208', 'Osamu Dazai');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('209', 'Kobo Abe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('210', 'Miyuki Miyabe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('211', 'Yasunari Kawabata');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('212', 'Fumiko Enchi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('213', 'Shusaku Endo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('214', 'Banana Yoshimoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('215', 'Mitsuyo Kakuta');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('216', 'Hiromi Kawakami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('217', 'Mieko Kawakami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('218', 'Kazuo Ishiguro');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('219', 'Yoko Ogawa');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('220', 'Higashino Keigo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('221', 'Natsuo Kirino');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('222', 'Kyoko Nakajima');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('223', 'Yoko Tawada');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('224', 'Ryu Murakami');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('225', 'Takashi Hiraide');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('226', 'Yoko Hayashi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('227', 'Higuchi Ichiyo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('228', 'Kanoko Okamoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('229', 'Yoko Sano');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('230', 'Kyoka Izumi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('231', 'Machiko Kyo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('232', 'Yoshiko Yuasa');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('233', 'Taiko Hirabayashi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('234', 'Tamiki Hara');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('235', 'Fuyumi Ono');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('236', 'Shinobu Hashimoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('237', 'Ibuki Fujioka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('238', 'Takaaki Yoshimoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('239', 'Kyohei Murayama');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('240', 'Ayako Sono');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('241', 'Ishiro Honda');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('242', 'Hiroshi Inagaki');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('243', 'Nobuko Yoshiya');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('244', 'Kazuko Okamoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('245', 'Yumi Unita');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('246', 'Kohei Tsuka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('247', 'Kazuo Umezu');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('248', 'Hikaru Okuizumi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('249', 'Yasushi Akimoto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('250', 'Yasuo Uchida');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('301', 'Mark Twain');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('302', 'Ernest Hemingway');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('303', 'F. Scott Fitzgerald');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('304', 'Harper Lee');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('305', 'John Steinbeck');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('306', 'J.D. Salinger');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('307', 'Toni Morrison');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('308', 'Maya Angelou');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('309', 'Ray Bradbury');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('310', 'Kurt Vonnegut');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('311', 'Philip Roth');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('312', 'Sylvia Plath');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('313', 'Stephen King');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('314', 'Alice Walker');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('315', 'Herman Melville');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('316', 'Edgar Allan Poe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('317', 'H.P. Lovecraft');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('318', 'Emily Dickinson');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('319', 'Langston Hughes');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('320', 'T.S. Eliot');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('321', 'J.K. Rowling');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('322', 'George R.R. Martin');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('323', 'John Grisham');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('324', 'Dan Brown');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('325', 'Don DeLillo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('326', 'David Foster Wallace');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('327', 'Tom Clancy');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('328', 'George Orwell');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('329', 'Ayn Rand');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('330', 'Kazuo Ishiguro');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('331', 'Jhumpa Lahiri');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('332', 'Sandra Cisneros');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('333', 'Jonathan Franzen');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('334', 'Michael Chabon');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('335', 'Donna Tartt');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('336', 'Paul Auster');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('337', 'Jonathan Safran Foer');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('338', 'Zadie Smith');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('339', 'David Sedaris');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('340', 'Chimamanda Ngozi Adichie');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('341', 'Ta-Nehisi Coates');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('342', 'John Green');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('343', 'Gillian Flynn');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('344', 'George Saunders');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('345', 'Colson Whitehead');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('346', 'Jodi Picoult');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('347', 'Celeste Ng');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('348', 'Jennifer Egan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('349', 'Anthony Doerr');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('350', 'Paulo Coelho');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('401', 'Kim Young-ha');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('402', 'Shin Kyung-sook');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('403', 'Hwang Sok-yong');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('404', 'Han Kang');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('405', 'Lee Seung-u');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('406', 'Kim Hoon');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('407', 'Choi In-hun');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('408', 'Gong Ji-young');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('409', 'Jeon Gyeong-rin');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('410', 'Bae Suah');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('411', 'Hwang Kyung Shin');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('412', 'Yi Mun-yol');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('413', 'Kim Ae-ran');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('414', 'Kang Young-sook');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('415', 'Choi Eun');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('416', 'Park Min-gyu');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('417', 'Oh Jung-hee');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('418', 'Yi Kwang-su');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('419', 'Choi Soo-young');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('420', 'Jang Eun-jin');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('421', 'Kim Tong-ni');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('422', 'Park Wan-suh');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('423', 'Kim Eun-jung');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('424', 'Yi Sang');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('425', 'Kim Jin-myeong');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('426', 'Kim In-suk');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('427', 'Choe Yun');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('428', 'Ha Ilji');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('429', 'Jung Mi-kyung');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('501', 'Tim Winton');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('502', 'Colleen McCullough');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('503', 'Peter Carey');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('504', 'Liane Moriarty');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('505', 'David Malouf');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('506', 'Christos Tsiolkas');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('507', 'Hannah Kent');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('508', 'Richard Flanagan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('509', 'Geraldine Brooks');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('510', 'Markus Zusak');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('511', 'Kate Grenville');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('512', 'Thomas Keneally');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('513', 'Charlotte Wood');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('514', 'David Marr');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('515', 'Sonya Hartnett');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('516', 'Tara June Winch');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('517', 'Helen Garner');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('518', 'Jackie French');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('519', 'Andrew McGahan');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('520', 'David Williamson');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('521', 'Rachael Johns');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('522', 'Melina Marchetta');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('523', 'Morris Gleitzman');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('524', 'Fiona McIntosh');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('525', 'John Marsden');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('526', 'Garth Nix');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('527', 'Kate Morton');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('528', 'Andy Griffiths');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('529', 'Margaret Atwood');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('601', 'George Orwell');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('602', 'Gabriel García Márquez');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('603', 'J.K. Rowling');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('604', 'Fyodor Dostoevsky');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('605', 'Jane Austen');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('606', 'Franz Kafka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('607', 'J.R.R. Tolkien');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('608', 'Leo Tolstoy');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('609', 'Virginia Woolf');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('610', 'Hermann Hesse');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('611', 'Aldous Huxley');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('612', 'Gustave Flaubert');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('613', 'Agatha Christie');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('614', 'Leoš Janáček');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('615', 'Italo Calvino');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('616', 'Hans Christian Andersen');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('617', 'Miguel de Cervantes');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('618', 'John Keats');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('619', 'Arthur Conan Doyle');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('620', 'Anton Chekhov');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('621', 'Albert Camus');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('622', 'Joseph Conrad');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('623', 'Voltaire');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('624', 'Dante Alighieri');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('625', 'Euripides');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('626', 'Victor Hugo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('627', 'Thomas Mann');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('628', 'Homer');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('629', 'Henrik Ibsen');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('630', 'Molière');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('631', 'Johann Wolfgang von Goethe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('632', 'Alexandre Dumas');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('633', 'Giovanni Boccaccio');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('634', 'Charles Dickens');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('635', 'James Joyce');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('636', 'Emily Brontë');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('637', 'Leoš Janáček');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('638', 'John Milton');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('701', 'Chinua Achebe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('702', 'Wole Soyinka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('703', 'Ngũgĩ wa Thiongo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('704', 'Chimamanda Ngozi Adichie');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('705', 'Nawal El Saadawi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('706', 'Nadine Gordimer');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('707', 'Ben Okri');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('708', 'Sembene Ousmane');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('709', 'Bessie Head');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('710', 'Naguib Mahfouz');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('711', 'Leila Aboulela');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('712', 'Mariama Bâ');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('713', 'Chigozie Obioma');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('714', 'Alain Mabanckou');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('715', 'Tsitsi Dangarembga');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('716', 'Ayòbámi Adébáyò');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('717', 'Buchi Emecheta');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('718', 'Chinweizu Ibekwe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('719', 'Nuruddin Farah');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('720', 'Helon Habila');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('721', 'Dinaw Mengestu');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('722', 'Ama Ata Aidoo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('723', 'Ousmane Sembène');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('724', 'Nawal El Saadawi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('725', 'Chris Abani');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('726', 'Tayeb Salih');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('727', 'Koleka Putuma');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('728', 'Kwame Anthony Appiah');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('729', 'Mia Couto');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('730', 'Abdulrazak Gurnah');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('731', 'Zakes Mda');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('732', 'Ahmadou Kourouma');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('733', 'Yvonne Vera');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('734', 'Mũkoma wa Ngũgĩ');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('735', 'Grace Ogot');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('736', 'Alex La Guma');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('737', 'Dambudzo Marechera');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('738', 'Sony Labou Tansi');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('739', 'Cheikh Hamidou Kane');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('740', 'Birago Diop');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('741', 'Veronique Tadjo');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('742', 'Fiston Mwanza Mujila');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('743', 'Fatou Diome');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('744', 'Ogot obila kelo Samson');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('745', 'Chenjerai Hove');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('801', 'Catherine Lim');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('802', 'Kuo Pao Kun');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('803', 'Arthur Yap');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('804', 'Goh Poh Seng');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('805', 'Fong Hoe Fang');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('806', 'Siti Murni bt Mahmood');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('807', 'Meira Chand');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('808', 'Claire Tham');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('809', 'Ovidia Yu');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('810', 'Alfian Saat');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('811', 'Heng Siok Tian');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('812', 'Gopal Baratham');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('813', 'Yeng Pway Ngon');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('814', 'Yeo Wei Wei');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('815', 'Jeremy Tiang');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('816', 'Chia Hearn Chek');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('817', 'Lee Tzu Pheng');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('818', 'Chandran Nair');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('819', 'Tan Kok Seng');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('820', 'Colin Cheong');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('901', 'Johann Wolfgang von Goethe');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('902', 'Franz Kafka');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('903', 'Thomas Mann');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('904', 'Heinrich Heine');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('905', 'Hermann Hesse');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('906', 'Bertolt Brecht');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('907', 'Rainer Maria Rilke');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('908', 'Günter Grass');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('909', 'Hans Fallada');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('910', 'Gottfried Benn');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('911', 'Ingeborg Bachmann');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('912', 'Günter Kunert');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('913', 'Christa Wolf');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('914', 'Erich Maria Remarque');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('915', 'Anna Seghers');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('916', 'Wolfgang Borchert');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('917', 'Elfriede Jelinek');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('918', 'Günter de Bruyn');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('919', 'Wolfgang Koeppen');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('920', 'Theodor Fontane');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('921', 'Max Frisch');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('922', 'Herta Müller');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('923', 'Friedrich Dürrenmatt');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('924', 'Hans Magnus Enzensberger');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('925', 'Gisela Elsner');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('926', 'Christoph Hein');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('927', 'Uwe Johnson');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('928', 'E.T.A. Hoffmann');
INSERT INTO "pengarang" ("id_pengarang", "nm_pengarang") VALUES ('929', 'Johann Nestroy');
